# -*- coding: utf-8 -*-
"""ECE143-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18IteshJlOgGl0SvGCAzSgGavQ68vH2Go

# The below code imports all the required libraries required for this analysis.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
plt.style.use('seaborn')

"""#Reading in the data:"""

import pandas as pd

missing=["No Info","None","none"]
df=pd.read_csv("/content/CAX_Startup_Data.csv",na_values=missing)
df.head()
print(df.columns.values)

"""#The below code implements various attributes related to the founder vs the succcess rate are plotted."""

# columns related to founders and co-founders
cat_columns=["Average size of companies worked for in the past",'Worked in top companies',
"Have been part of startups in the past?","Have been part of successful startups in the past?","Consulting experience?","Exposure across the globe",
"Breadth of experience across verticals","Highest education",'Average Years of experience for founder and co founder',
"Relevance of education to venture","Relevance of experience to venture","Degree from a Tier 1 or Tier 2 university?",
"Experience in selling and building products","Top management similarity","Number of  of Research publications","Years of education",
"Experience in Fortune 100 organizations","Experience in Fortune 500 organizations","Experience in Fortune 1000 organizations"]
font={'weight' : 'bold',
        'size': 16}
q=1
plt.figure(figsize=(15,80))
for j in cat_columns:
    plt.subplot(10,2,q)
    ax=sns.countplot(df[j].dropna(),palette="Paired",hue=df["Dependent-Company Status"])
    plt.xticks(**font)
    plt.yticks(**font)
    plt.xlabel(j)
    for i in ax.patches:
        ax.text(i.get_x(),i.get_height()+3,str(round((i.get_height()), 2)), fontsize=12, color='Black')
    q+=1
plt.show()

"""#Keytake Aways


1.   If the founders had exposure across the globe, it increased the success rate of the startup by a lot.
2.   If the founder had relevance to venture, then the startup’s success rate increases a lot. Almost 83% of all successful startup founders had previous experience in venture capital.
3. If the founders have already a prior experience in selling and building products, the chances of these startups succeeding increases a lot.






"""
