# -*- coding: utf-8 -*-
"""Internet Activity and Number of Companies vs. Status

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aEmXAQZm0Xcp0EXqVoDLKCfKR56Js4cn
"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('CAX_Startup_Data.csv')
success_greater_500_num = len(df[(df["Internet Activity Score"] > 500) & 
                                 (df["Dependent-Company Status"] == "Success")])
failure_greater_500_num = len(df[(df["Internet Activity Score"] > 500) & 
                                 (df["Dependent-Company Status"] == "Failed")])
greater_than_500_internet_num = success_greater_500_num + failure_greater_500_num
success_perc = success_greater_500_num / greater_than_500_internet_num
failure_perc = failure_greater_500_num / greater_than_500_internet_num
df = pd.DataFrame({'percentages': [success_perc, failure_perc]}, 
                  index=['Successful companies', 'Failed companies'])
df.plot(kind='pie', y='percentages', autopct='%1.2f%%', legend=False, startangle=160)
plt.title('Companies with an internet activity score greater than 500')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('CAX_Startup_Data.csv')
df.plot.scatter(x="Employee Count", y="Dependent-Company Status", title="Number of Companies vs. Company Status")

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('CAX_Startup_Data.csv')
df.plot.bar(x="Employees per year of company existence")