# -*- coding: utf-8 -*-
"""ECE143.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HWd8r_yUUwHqSOM0xZMFYmbFF3vihqtc

# Required Dependencies:
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
plt.style.use('seaborn')

"""# Data preprocessing"""

import pandas as pd

missing=["No Info","None","none"]
df=pd.read_csv("/content/CAX_Startup_Data.csv",na_values=missing)
df.head()
print(df.columns.values)

df=df[['Dependent-Company Status','Percent_skill_Entrepreneurship' ,'Percent_skill_Operations',
 'Percent_skill_Engineering', 'Percent_skill_Marketing',
 'Percent_skill_Leadership' ,'Percent_skill_Data Science',
 'Percent_skill_Business Strategy', 'Percent_skill_Product Management',
 'Percent_skill_Sales', 'Percent_skill_Domain', 'Percent_skill_Law',
 'Percent_skill_Consulting' ,'Percent_skill_Finance',
 'Percent_skill_Investment']]

df=df[(df['Percent_skill_Entrepreneurship']>10) | (df['Percent_skill_Operations']>10) | (df['Percent_skill_Engineering']>10) | (df['Percent_skill_Marketing']>10) | (df['Percent_skill_Leadership']>10) | (df['Percent_skill_Data Science']>10) | (df['Percent_skill_Business Strategy']>10) | (df['Percent_skill_Product Management']>10) | (df['Percent_skill_Sales']>10) | (df['Percent_skill_Domain']>10) | (df['Percent_skill_Law']>10) | (df['Percent_skill_Consulting']>10) | (df['Percent_skill_Finance']>10) | (df['Percent_skill_Investment']>10)]

# Remove the NaN values

import numpy as np

df=df.fillna(np.nan)

null=pd.DataFrame(df.isnull().sum(),columns=["Null Values"])
null["% Missing Values"]=(df.isna().sum()/len(df)*100)
null.style.background_gradient(cmap='viridis',low =0.2,high=0.1)

cat_columns=['Dependent-Company Status','Percent_skill_Entrepreneurship' ,'Percent_skill_Operations',
 'Percent_skill_Engineering', 'Percent_skill_Marketing',
 'Percent_skill_Leadership' ,'Percent_skill_Data Science',
 'Percent_skill_Business Strategy', 'Percent_skill_Product Management',
 'Percent_skill_Sales', 'Percent_skill_Domain', 'Percent_skill_Law',
 'Percent_skill_Consulting' ,'Percent_skill_Finance',
 'Percent_skill_Investment']

 # columns related to founders and co-founders
font={'weight' : 'bold',
        'size': 16}
q=1
plt.figure(figsize=(15,80))
for j in cat_columns:
    plt.subplot(10,2,q)
    ax=sns.countplot(df[j].dropna(),hue=df["Dependent-Company Status"])
    #ax=sns.countplot(df[j].dropna(),palette="Paired",hue=df["Dependent-Company Status"])
    plt.title("year of founding",**font)
    plt.ylabel("count of companies")
    plt.xticks(rotation=45)
    for i in ax.patches:
        # get_x pulls left or right; get_height pushes up or down
        ax.text(i.get_x(), i.get_height()+2, \
                str(round((i.get_height()), 2)), fontsize=14, color='dimgrey')
    q+=1
plt.show()

"""# Results:"""

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Entrepreneurship')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Operations')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Engineering')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Marketing')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Data Science')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Leadership' )\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Business Strategy')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Product Management')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Sales')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Domain')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Law')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Consulting')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Finance')\
    .add_legend()
plt.show()

sns.FacetGrid(df,hue='Dependent-Company Status',height=6)\
    .map(sns.distplot,'Percent_skill_Investment')\
    .add_legend()
plt.show()

"""# Key Take Aways:
1. In this slide, the plots represent the Percentage of skill in the company vs the success rate of the company. For all the Skills, represented on the slide, most distributions have no difference between success rate and failure rate.
2. But, for Business strategy and product development, more the people employed in these departments, the success rate of startup decreases. An interpretation is that if that the startup focuses more on the Business strategy rather than on the product creation, the success rate decreases.
"""
